export default interface IEmpresa {
    id: number
    nomeFantasia: string
    optante: string
    razaoSocial: string
    cnpj: string
    onlyNumberCNPJ: string
    inscricaoEstadual: string
    inscricaoMunicipal: string
    endereco: string
    cep: string
    bairro: string
    cidade: string
    uf: string
    codCidade: string
    nro: string
    complemento: string
    usuarioDono: string
    statusPagamento: boolean
    tokenCertificado: string
    versao: number
    liberaBackup: boolean
    dataCriacao: Date
    vendedor: string
    certificado: string
    senhaCertificado: string
    inicioPagamento: Date
    diaCobranca: number
    email: string
    telefone: string
    valorMensal: number
    valorKrd: number
    formaPagamento: string
    isMatriz: boolean
    assessoria: boolean
    usuarioContador: string
    idChatTelegram: number
    sendVendas: boolean
    idChatWhatsapp: string
    usuarioSupervisor: string
    cfmToken: string
    slug: string
    // Novos campos de automação
    plano: 'Teste' | 'Mensal' | 'Semestral' | 'Anual'
    geraBoleto: boolean
    geraNfse: boolean
    enviaEmail: boolean
    enviaSms: boolean
}